export const ISEF_CATEGORIES = [
  { value: 'ANIM', label: 'Animal Sciences' },
  { value: 'BEHA', label: 'Behavioral and Social Sciences' },
  { value: 'BCHM', label: 'Biochemistry' },
  { value: 'BMED', label: 'Biomedical and Health Sciences' },
  { value: 'ENBM', label: 'Biomedical Engineering' },
  { value: 'CELL', label: 'Cellular and Molecular Biology' },
  { value: 'CHEM', label: 'Chemistry' },
  { value: 'CBIO', label: 'Computational Biology and Bioinformatics' },
  { value: 'EAEV', label: 'Earth and Environmental Sciences' },
  { value: 'EBED', label: 'Embedded Systems' },
  { value: 'EGSD', label: 'Energy: Sustainable Materials and Design' },
  { value: 'ETSD', label: 'Engineering Technology: Statics and Dynamics' },
  { value: 'ENEV', label: 'Environmental Engineering' },
  { value: 'MATS', label: 'Materials Science' },
  { value: 'MATH', label: 'Mathematics' },
  { value: 'MCRO', label: 'Microbiology' },
  { value: 'PHYS', label: 'Physics and Astronomy' },
  { value: 'PLNT', label: 'Plant Sciences' },
  { value: 'ROBO', label: 'Robotics and Intelligent Machines' },
  { value: 'SOFT', label: 'Systems Software' },
  { value: 'TECA', label: 'Technology Enhances the Arts' },
  { value: 'TMED', label: 'Translational Medical Science' },
]
